/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HTScenery': RouteRecordInfo<
      '/posts/HTScenery',
      '/posts/HTScenery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MachineLearning': RouteRecordInfo<
      '/posts/MachineLearning',
      '/posts/MachineLearning',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MCU/Esp32Dev1': RouteRecordInfo<
      '/posts/MCU/Esp32Dev1',
      '/posts/MCU/Esp32Dev1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MCU/STM32': RouteRecordInfo<
      '/posts/MCU/STM32',
      '/posts/MCU/STM32',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/META': RouteRecordInfo<
      '/posts/META',
      '/posts/META',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.1_4ef9edfe41a606df1b5bf1ce270c4f15/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@1.0.0-rc.1_@babel+pa_ac868b0ca98f01bb873b75424d473e8c/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.1_4ef9edfe41a606df1b5bf1ce270c4f15/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@1.0.0-rc.1_4ef9edfe41a606df1b5bf1ce270c4f15/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/HTScenery.md': {
      routes:
        | '/posts/HTScenery'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/MachineLearning.md': {
      routes:
        | '/posts/MachineLearning'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/MCU/Esp32Dev1.md': {
      routes:
        | '/posts/MCU/Esp32Dev1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/MCU/STM32.md': {
      routes:
        | '/posts/MCU/STM32'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/META.md': {
      routes:
        | '/posts/META'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
